### ISSUE TITLE
Advenced reverting

### ISSUE THREAD

**Issue by Eiji7** [smpallen99/whatwasit#12]
These methods can be useful:

1. revert_last_version - reverts last change (only update) - returns tuple: `{:ok, version}` or raise `Whatwasit.NoUpdateVersionError`
2. revert_to_version - revert all changes from X version
3. revert_by_whodoneit (when whodoneite is a `Enum`)
4. revert_by_whodoneit - calls: `revert_by_whodoneit([whodoneit])`
5. revert_by_sql (sql part that for example do search in map; adequately to point 3)

For 3rd and 4th point:
revert all changes made by `User`(s)
returns tuple: `{:ok, versions}` or `{:error, whodoneit}` or raise `Whatwasit.NoUpdateVersionError`
where: `whodoneit` is `User` `Enum` that made changes after one or more changes made by selected whodoneit(s).
Optionally: force parameter that not return error tuple and delete all versions (from selected whodoneit(s) first update version).

This can be done in optional module:
```elixir
defmodule MyProject.Post do
    use Whatwasit
    use Whatwasit.Revert
    # ...
end
```

Maybe optionally add `is_deleted` field for `Version` (to preview admin activity)? What do you think about it?

**Comment by smpallen99** [comment]
Yes, I was thinking of adding revert support at some time. Couple notes:

* I find revert_by_assocation(s) a little confusing. Perhaps revert_by_whodoneit(s)??
* These functions should be added to the generated Version model. 

Steve

**Comment by Eiji7** [comment]
Yes, you're right. I edited my issue and added one more method (point 5).
