### ISSUE TITLE
Question: why migration and model are generated?

### ISSUE THREAD

**Issue by Eiji7** [smpallen99/whatwasit#15]
In migration we can easily add if statement for app config.

I know that calculating `changeset_fields` and `schema_fields` on each request is not a good idea.
Is saving them in configuration (or :ets) after app start (and before listen for requests) and read them in model is bad idea?
Now we have: `version.ex` and `version_map.ex` templates.
They are similar and could be written at once with some if's (based on app config).

What do you think about it?

**Comment by smpallen99** [comment]
I don't really understand most of your comment. However, your right, there is a lot of duplicate code between `version.ex` and `version_map.ex`. I agree, it should be refactored into one.

**Comment by Eiji7** [comment]
I'm preparing to help you maintain this code. I'm new in elixir/erlang, but I had lots of hours in ruby/rails (MVC and other things are not problem for me). I will ask some questions to elixir forum for complete my knowlegde about how ecto works (changeset, migrations, callbacks). I want to resolve all my issues, but don't know how long it will take.

**Comment by Eiji7** [comment]
#17
