### ISSUE TITLE
Fork: Refactor and simplify code

### ISSUE THREAD

**Issue by Eiji7** [smpallen99/whatwasit#17]
TODO:

1. Better code configuration
2. Better code modularization
3. No code duplication
4. No code generation (by templates)
5. Remove install task

**Comment by smpallen99** [comment]
@Eiji7 Thanks for taking this on!! 

Few requests...

* Can you break this up into multiple issues with corresponding PRs
* I'm ok with with a default configuration that does not require code generator or an install task. However, I created generated code for customization purposes. So, I think I would like to review new implementation before removing mix generators.

**Comment by Eiji7** [comment]
1. Ok. I will update this and provide more info in separeted issues in next days.
2. My code should me much more configurable than you, so don't worry about this :-). Of course any tips are welcome.

First commit should be uploaded in this or next week.

**Comment by Eiji7** [comment]
Hmmm, I have a problem with relations. I have good code (only initial work now ie. relations only). It already works except [preload](https://elixirforum.com/t/ecto-preload-problem-with-multiple-prefix-setup/1539). I want to solve this by relations, because I think it's more "ecto like". I need a prefix, because I don't want to conflict with data in project database. More info I provide after solve this isssue.

**Comment by Eiji7** [comment]
Ok, I started some things (initial work) see [my project page](https://github.com/Eiji7/whatwasit).
I need to add implementation to all **TODO** comments + implement things from my issues + documentation + new tests.
More info I provide tomorrow.
I created the code from scratch, so they can be there still shortcomings (eg. unnecessary mix dependencies). Any tips are welcome 😄.

**Comment by Eiji7** [comment]
@smpallen99: Still no response ... I will continue in next week (ie. two weeks after initial commit) without waiting for you.
After next two weeks (and no response from you) I will create my new project from my last commit in this project.
I know you are very busy, but I can't wait any longer for approve my changes by you.

**Comment by smpallen99** [comment]
@Eiji7 Sorry for the delay getting back to you. I'll take a look in the next couple days.

Steve

**Comment by Eiji7** [comment]
@smpallen99: uff, you find some time for this project, thanks :smile

**Comment by smpallen99** [comment]
@Eiji7 I took a quick look at your branch. Give that your using different different base name and non-standard elixir source indentation, I think its best that you create your own package. I just ask that you use a different and distinct name for your package.

**Comment by Eiji7** [comment]
1. "non-standard elixir source indentation"<br/>
I use "[elastic tabs](https://elixirforum.com/t/tabs-vs-spaces/753/9?u=eiji)"<br/>
It's not a problem to replace all "\t" to "  " and push it as a "fix".
2. "Give that your using different different base name"<br/>
Sorry for that. I generated some code like: "what_was_it" (by mix phoenix.new) intead of "whatwasit" and then copy it to my code and finally modify it. Also one replace can fix that.

I mean something else. I asked about ways to solve some things. For example my config implementation (instead of generating code from template) or using protocol for diffs. I want to got comment about how code works (not how it looks). See, this is my first real project code. I know some things will be to correct, but I was asking for other things.

I have no problem if you want to move my code to separated project. I can find other name, so don't worry about it. At end I just want to got your comment about how my code works, so I can continue to implement things I begin (a TODO comments) or reimplement some things (but practice like useless macro uses).
